language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t caitwarnberg/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true caitwarnberg/docker-react npm run test